Resources list
CRiquelme/cap-frontend pull request #12
Opened 2022-10-03 17:04 UTC by CRiquelme

Listado de recursos de los learning units con sus valoraciones.

2022-10-03 19:19 UTC, PabloAbara requested changes

2022-10-03 19:19 UTC, PabloAbara commented on src/components/resources-list/ResourcesList.js
> +import ResourcesListItem from './ResourcesListItem';
dejar el import con variables globales

2022-10-03 19:19 UTC, PabloAbara commented on src/components/resources-list/ResourcesList.js
> +const ResourcesList = () => {
Creo que este componente debiera recibir un Array de Resources, por lo que los hooks de data debieran ocurrir en el componente Padre (o no?)

2022-10-03 19:19 UTC, PabloAbara commented on src/components/resources-list/ResourcesListItem.js
> +const ResourcesListItem = ({ resourceUnits }) => {
creo que el nombre del parámetro debiera ser "resource" a secas, para seguir en la lógica que el componente padre pasa un Array de resources y este recibe un resource

2022-10-03 19:19 UTC, PabloAbara commented on src/components/resources-list/ResourcesListItem.js
> +          <img src={`images/product/${resourceUnits.image}`} onError={(e) => (e.target.src = 'https://www.primefaces.org/wp-content/uploads/2020/05/placeholder.png')} alt={resourceUnits.name} />
Se puede corregir? Es cambiar el img a Image (creo que ocupo una también)

2022-10-03 19:19 UTC, PabloAbara commented on src/hooks/useResources.js
> +import useSWR from 'swr';
Como conversamos, me parece que la lógica del router no debiese ir acá

2022-10-03 19:19 UTC, PabloAbara commented on src/pages/learning-units/[id].js
> +const resources = () => {
Agregar acá lo del Router y request para rescatar los resources.

2022-10-04 14:29 UTC, CRiquelme commented on src/components/resources-list/ResourcesListItem.js
> +          <img src={`images/product/${resourceUnits.image}`} onError={(e) => (e.target.src = 'https://www.primefaces.org/wp-content/uploads/2020/05/placeholder.png')} alt={resourceUnits.name} />
Se puede mantener como ahora mientras.

2022-10-04 14:30 UTC, CRiquelme commented on src/components/resources-list/ResourcesListItem.js
> +const ResourcesListItem = ({ resourceUnits }) => {
Lo tengo para resolver en un siguiente cambio

2022-10-04 20:59 UTC, PabloAbara approved these changes
Como comentamos, sugiero abstraer a otro componente la lógica del Modal de Add Resource. Doy por validado el código relacionado al DataView.

2022-10-04 20:59 UTC, PabloAbara commented on src/components/resources-list/ResourcesList.js
> +  const { resources, isLoadingResources, isErrorResources } = useResources({ learningUnitId });
¿Por qué hay que mandarlo des-estructurado?

2022-10-04 21:09 UTC, merged